fieldLayouts:
  5572c205-cf50-45ec-a86d-fda8d17dbc5d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 912d5ff8-1bdd-4d9d-9f0f-73d87cbeaffb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a79e18ee-bb78-4568-be9c-24ed22fc3be1 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46968876-4e79-4e7d-aeee-29c3a38262f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2bd45805-6b4f-44e5-abbe-e7b9d9486620 # Hero Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8009fea4-24bf-420c-8893-a6635528c300
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: b22795ce-d43e-462e-b46b-7465194dd5ba
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f964a032-555a-401e-99df-fbbe1aff6d16 # Slider Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7859fac1-757e-412a-ba5e-3499a8a6d701
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80118ba7-6f10-4eec-b489-5f775d7f82bb # Slider Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20e63bf3-15b5-45c3-8d39-b48692430dbb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 560bd468-1d66-4847-bfb7-7f59d24e7aaa # Slider Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee19bf47-dad4-4796-8997-4b856aadf812
            userCondition: null
            warning: null
            width: 100
        name: Slider
        uid: 08355518-dc37-47f4-813b-d52ce507eed7
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: fec291cf-9bbc-46ad-b520-97b67bbcc7e9 # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
