columnSuffix: bwxxppql
contentColumnType: text
fieldGroup: 46590a8c-c519-4611-a669-d23b84066f7d # Homepage
handle: sliderTitle
instructions: 'Title for the slider'
name: 'Slider Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
