defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  10cd244d-1065-43ca-aee5-e227035c5887: # Imagic Ddev
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
